Add new STM32F4 and measured boot example
wolfSSL/wolfBoot-examples pull request #4
Opened 2020-12-18 23:52 UTC by tomoveu

This PR has three goals:
- Add wolfBoot-example for STM32F4
- Add measured boot example
- Use TLS1.3 to communicate over the internet

This example is based on the existing Kinetis K64 FreeRTOS example with three differences:
- It uses STM32F4-Discovery and extension modules for internet connectivity
- It uses TPM SLB9670
- It does not have HTTPS server, but a HTTPS client

There are simpler ways measured boot could be demonstrated, for security reasons, the possibility to store the golden value in the same flash region as wolfBoot is disregarded, although it was a very nice and simple demo.

Instead, chosen is the most typical scenario, where the tamper-proofed log from the TPM PCR is reported to a remote server. Then, it is up to the remote server to perform evaluation against golden values and take actions, if necessary.

In future, this example could be enhanced by storing the golden value in the TPM and this would require adding TPM localities to wolfTPM.

Signed-off-by: Dimitar Tomov <dimi@wolfssl.com>

2020-12-20 15:27 UTC, tomoveu commented
Quick update: The STM32F4BB Baseboard is no longer in manufacturing, therefore I ordered the STM32F4WIFI extension board. Using WiFi would require me to add extra code(driver), but will make the example use currently available STM32 hardware, so everyone could use it :)

2021-01-26 11:12 UTC, tomoveu commented
@danielinux This is ready for testing.

Occasionally, I get "isr_fault" due to the jump wires between my STM32 and TPM. I want to solder my TPM like you have done.

Make sure the wolfTPM submodule in wolfBoot is fetched as well. This is the 1st wolfboot-example that requires wolfTPM 💡  

Example README here, UART pinout, TPM pinout - https://github.com/tomoveu/wolfBoot-examples/tree/add-stm32f4-example/test-app-STM32F4-measured-boot#compiling

2021-01-27 01:50 UTC, dgarske requested changes
Just a few minor things at first glance. I plan to setup and test this tomorrow.

2021-01-27 01:50 UTC, dgarske commented on test-app-STM32F4-measured-boot/src/app_stm32f4.c
> +/* stm32f4.c
Please update the filename and description.

2021-01-27 01:50 UTC, dgarske commented on test-app-STM32F4-measured-boot/src/app_stm32f4.c
> +    memset(rxBuf, 0, xferSz);
Consider using XMEMSET for consistency.

2021-01-27 01:50 UTC, dgarske commented on test-app-STM32F4-measured-boot/src/app_stm32f4.c
> +volatile uint32_t testme = 1;
I prefer globals at the top of file. Also if not being extern'd please make static.

2021-01-27 01:50 UTC, dgarske commented on test-app-STM32F4-measured-boot/src/app_stm32f4.c
> +void main(void) {
Brace on new line for functions.

2021-01-27 17:08 UTC, tomoveu commented on test-app-STM32F4-measured-boot/src/app_stm32f4.c
> +void main(void) {
Typo. Thanks for catching it.

2021-01-27 17:08 UTC, tomoveu commented on test-app-STM32F4-measured-boot/src/app_stm32f4.c
> +volatile uint32_t testme = 1;
Moved and made static.

2021-01-27 17:08 UTC, tomoveu commented on test-app-STM32F4-measured-boot/src/app_stm32f4.c
> +    memset(rxBuf, 0, xferSz);
Will do.

2021-01-27 17:08 UTC, tomoveu commented on test-app-STM32F4-measured-boot/src/app_stm32f4.c
> +/* stm32f4.c
Thanks.

2021-01-27 17:39 UTC, tomoveu commented
@dgarske thank you for the review 🤝 

I have made the requested changes. I also extended the README file and added my openocd config.

Please make sure the wolfTPM submodule in wolfBoot is fetched as well, because this is the first wolfboot-example that requires wolfTPM 😃

2021-01-27 23:29 UTC, dgarske approved these changes
Over to @danielinux for final. Consider merging PR https://github.com/wolfSSL/wolfBoot/pull/103 and updating the wolfBoot example submodule.

2021-02-02 10:40 UTC, danielinux requested changes
This looks great. I only have one request. Can the '.bmp' image in the README be in a compressed format (e.g. png) to reduce size?

2021-02-02 11:22 UTC, tomoveu commented
Sure. I will convert it and force-push to have clean git history

2021-02-02 14:17 UTC, danielinux approved these changes

2021-02-02 14:17 UTC, merged