examples: add new qemu x86 FSP examples
wolfSSL/wolfBoot-examples pull request #8
Opened 2023-01-18 19:32 UTC by rizlik

adding the necessary script to create FSP binaries to boot qemu x86 q35 machine from the resect vector.
It uses the wolfBoot PR:

2023-01-23 15:26 UTC, danielinux requested changes

2023-01-23 15:26 UTC, danielinux commented on qemu-x86-fsp-linux/build_qemu_fsp.sh
> +#!/bin/sh
please change to `#!/bin/bash`

2023-01-23 15:26 UTC, danielinux commented on qemu-x86-fsp-linux/build_and_run_example.sh
> +git clone "$WOLFBOOT_REPO" wolfBoot
Please use the existing submodule in `../wolfboot` instead

2023-01-26 11:41 UTC, rizlik commented
addressed comment + fixed error in edk2 build system .map file parser

2024-09-23 18:39 UTC, dgarske commented
@rizlik  What's the status of this PR? Is it ready to review/merge?

2024-09-24 13:37 UTC, rizlik commented
This is now a stale PR, a working example of FSP running on QEMU can be found in the main wolfBoot repo, see ```./tools/scripts/x86_fsp/qemu/test_qemu.sh``` in https://github.com/wolfSSL/wolfBoot/

2024-09-24 13:37 UTC, closed without merging